### ISSUE TITLE
go mod path

### ISSUE THREAD

**Issue by ro-ag** [urfave/sflags#25]
module declares its path as: github.com/sflags
	        but was required as: github.com/octago/sflags

go mod tidy fails

**Comment by ThinkChaos** [comment]
This is already fixed in the code by b0295b181745e638c11a781cd5d54815e23439e0. @octago can you please cut a new release with that fix?
This makes this module unusable without annoying workarounds and is clearly a common issue as all 3 current open PRs are for this: #23, #24, #26.

(Not sure @octago will tag the correct people, so adding @m0sth8)

**Comment by abitrolly** [comment]
@dearchap are we ready to cut a new release?

**Comment by dearchap** [comment]
@abitrolly yes. want to do the honours ?

**Comment by abitrolly** [comment]
@dearchap I don't remember a lot about importing and releasing Go libraries. I guess the lib needs a major version bump, and there is still possibility it breaks stuff. :D

**Comment by dearchap** [comment]
Made the release

**Comment by abitrolly** [comment]
Closing. Thanks everyone!
